#!/usr/bin/env python3
from __future__ import annotations
import json, hashlib
from datetime import datetime, timezone
from pathlib import Path

STATE=Path('data/cousteau/JANUS-HA10-SEAFLOOR-RECONSTRUCTION-STATE-002-2026-08-22-v1.0.json')
OUT=Path('data/cousteau/JANUS-HA10-SEAFLOOR-NEXT-COUNCIL-RUN-002-2026-08-22-v1.0.json')
state=json.loads(STATE.read_text(encoding='utf-8'))

result={
  'artifact_id':'JANUS-HA10-SEAFLOOR-NEXT-COUNCIL-RUN-002-2026-08-22-v1.0',
  'created_utc':datetime.now(timezone.utc).isoformat(),
  'question':'Given the frozen HA10 seafloor reconstruction state, what single next physical stage should JANUS authorize, what parallel archive work is allowed, and what corrections must be enforced before any morphology scoring?',
  'state_artifact':state['artifact_id'],
  'state_target_identity':state['governance']['target_identity'],
  'blockers':state['current_blockers'],
  'council':{
    'HRain':'PRIORITIZE_MISSING_PRIMARY_DEPTH_SURFACE_OVER_INTERPRETATION',
    'iNaiHR':'MAY_EXPAND_ARCHIVE_GRAPH_ONLY__NO_IDENTITY_WEIGHT',
    'DemiHead':'FAIL_CLOSED_IF_PRIMARY_RASTER_OR_GEOREFERENCE_IS_NOT_RECOVERED',
    'Fast_CAT':'NO_TARGET_SCORING_UNTIL_PREREG_AND_CONTROL_SET_ARE_LOCKED',
    'Aura':'ZERO_EVIDENCE_AUTHORITY',
    'Janus_Cosmos':'KEEP_FROZEN_COORDINATES_IMMUTABLE_AND_SEPARATE_GEOMETRY_FROM_CAUSATION',
    'Cousteau':'RECOVER_PRIMARY_BATHYMETRY_OR_AS_BUILT_SOUNDINGS_FIRST__BACKSCATTER_SECOND',
    'Fundamentum':'VOLCANIC_BASELINE_REMAINS_PRIMARY__NEGATIVE_RESULTS_PERSIST',
    'AIFC':'REQUIRE_SOURCE_URI_DATASET_ID_CRS_RESOLUTION_HASH_AND_TRANSFORM_FOR_EVERY_RECOVERED_TILE',
    'Voice_of_Janus':'LOCATE_THE_FLOOR__THEN_RECOVER_SHAPE__THEN_ACOUSTICS'
  },
  'janus_answer':{
    'AUTHORIZED_STAGE':'PRIMARY_SOURCE_RECOVERY_SWEEP_002',
    'PRIMARY_OBJECTIVE':'RECOVER_AT_LEAST_ONE_AUTHORITATIVE_DIGITAL_OR_GEOREFERENCED_SEAFLOOR_PRODUCT_INTERSECTING_A_FROZEN_HA10_TARGET',
    'PRIORITY_ORDER':[
      'BAS_NATIVE_NETCDF_OR_ASCII_FOR_GB_NERC_BAS_PDC_01236_AND_EXTRACT_H10N1_FIXED_CELL',
      'THALES_P2548_OR_ORIGINAL_2002_GEOREFERENCED_MBES_BACKSCATTER_FOR_H10S_TRIAD',
      'HA10_FINAL_AS_BUILT_OR_INSTALLATION_SURVEY_WITH_SEAFLOOR_DEPTHS_AT_FINAL_NODES',
      'BGS_MEDIN_OFFSHORE_GEOINDEX_HOLDINGS_FOR_ASCENSION_HA10_2002_SURVEY',
      'OCEANS_2003_ORIGINAL_AUTHOR_COLOR_FIGURES_ONLY_AS_A_BRIDGE_TO_PRIMARY_GEOREFERENCE'
    ],
    'PARALLEL_ALLOWED':[
      'CHECK_PUBLIC_ARCHIVES_AND_DATA_CATALOGS_FOR_EXACT_PRIMARY_FILE_ENDPOINTS',
      'PRESERVE_EXTERNAL_TICKETS_DH_2635_3872_AND_BGS_SPECIALIST_RESPONSE_AS_INDEPENDENT_CALIBRATION',
      'BUILD_PROVENANCE_MANIFEST_FOR_EVERY_RECOVERED_FILE_BEFORE_ANALYSIS'
    ],
    'DO_NOT_DO_YET':[
      'NO_WISHBONE_COORDINATE_ESTIMATION_FROM_TEXT_OR_SCREENSHOT',
      'NO_PYRAMIDALITY_OR_CRATER_SCORING',
      'NO_117_121HZ_IDENTITY_TEST',
      'NO_RETARGETING_WINDOWS_TO_MATCH_AVAILABLE_COVERAGE',
      'NO_USE_OF_2200M_DESIGN_ESTIMATE_AS_FINAL_SEAFLOOR_DEPTH'
    ],
    'SUCCESS_GATE':'ONE_PRIMARY_AUTHORITATIVE_GEOREFERENCED_OR_DIGITAL_SEAFLOOR_SURFACE_INTERSECTS_A_FROZEN_TARGET_AND_IS_REPRODUCIBLY_EXTRACTABLE',
    'ON_SUCCESS':'STOP_AND_ASK_JANUS_AGAIN_BEFORE_ANY_MORPHOLOGY_METRICS',
    'ON_FAILURE':'FREEZE_NEGATIVE_ARCHIVE_RECEIPT_AND_ASK_JANUS_FOR_NEXT_ARCHIVE_BRANCH',
    'TARGET_IDENTITY':'UNCONFIRMED'
  },
  'hard_rules':state['hard_rules'] + [
    'EVERY_NEWLY_RECOVERED_PRIMARY_FILE_GETS_PROVENANCE_MANIFEST_BEFORE_USE',
    'STOP_AFTER_PRIMARY_RECOVERY_AND_REASK_JANUS_BEFORE_SCORING'
  ]
}
result['sha256']=hashlib.sha256(json.dumps(result,sort_keys=True,separators=(',',':'),ensure_ascii=False).encode()).hexdigest()
OUT.parent.mkdir(parents=True,exist_ok=True)
OUT.write_text(json.dumps(result,indent=2,ensure_ascii=False),encoding='utf-8')
print(json.dumps(result,indent=2,ensure_ascii=False))
