#!/usr/bin/env python3
from __future__ import annotations
import argparse, json, math
from pathlib import Path

EXPECTED_RAW='761d163482a44da0cc417a325372d6f3de163669b099ecc2f64c02a3282bcc59'
EXPECTED_BLOCK='039b839861e515efe339542b8c57e5830bd484def961804f9c1fb61387132c3f'

def gate(state,evidence,failure=None):return {'state':state,'evidence':evidence,'failure':failure}
def main():
 ap=argparse.ArgumentParser();ap.add_argument('receipt',type=Path);ap.add_argument('--output',required=True,type=Path);a=ap.parse_args();d=json.loads(a.receipt.read_text(encoding='utf-8'));g={}
 raw=d['raw_source_integrity'];g['G0_RAW_INTEGRITY']=gate('PASS' if raw['raw_file_sha256']==EXPECTED_RAW and raw['target_block_sha256']==EXPECTED_BLOCK and raw['record_count']==14536 and raw['block_size_bytes']==40960 else 'FAIL',{'raw_file_sha256':raw['raw_file_sha256'],'target_block_sha256':raw['target_block_sha256'],'record_count':raw['record_count'],'block_size_bytes':raw['block_size_bytes']})
 cdf=d['prism_cdf_crosscheck'];same_time=(cdf['target_line_index']==raw['target_block_index'] and cdf['target_line_utc']==raw['target_block_utc']);g['G1_RAW_CDF_TIME_IDENTITY']=gate('PASS' if same_time else 'FAIL',{'raw_index':raw['target_block_index'],'raw_utc':raw['target_block_utc'],'cdf_index':cdf['target_line_index'],'cdf_utc':cdf['target_line_utc'],'cdf_nl':cdf['nl'],'raw_record_count':raw['record_count']})
 fm=d['raw_to_prism_format_mapping'];hv=d['factor8_heldout_validation'];layout_ok=(fm['best_layout']['bin_width']==8 and fm['best_layout']['bin_reducer']=='MEAN' and fm['best_layout']['raw_transform']=='ABS' and fm['best_layout']['side_order']=='STBD_THEN_PORT' and fm['best_layout']['starboard_reversed'] is True and fm['best_layout']['port_reversed'] is False and hv['mapping_retuned'] is False and hv['target_index_excluded'] is True and len(hv['indices'])==7)
 g['G2_RAW_TO_PRISM_LAYOUT']=gate('VALIDATED_FORMAT_MAPPING' if layout_ok else 'FAIL',{'frozen_layout':fm['best_layout'],'heldout_indices':hv['indices'],'mapping_retuned':hv['mapping_retuned'],'target_excluded':hv['target_index_excluded'],'heldout_observed_correlations':{'pearson_median':hv['pearson_median'],'pearson_min':hv['pearson_min'],'spearman_median':hv['spearman_median'],'spearman_min':hv['spearman_min']},'acceptance_threshold_used':None,'interpretation':'identity-level reproduction is recorded as a format-layout fact; no scientific anomaly threshold is inferred'})
 spacing=fm['raw_sample_spacing_m'];g['G3_RAW_SAMPLE_SPACING']=gate('CROSS_VALIDATED_FORMAT_SCALE' if spacing==0.75 and cdf['ns']==1000 else 'FAIL',{'raw_sample_spacing_m':spacing,'cdf_ns':cdf['ns'],'factor8_pixel_m':fm['external_prism_resolution_documentation']['factor_8_pixel_m'],'full_resolution_pixel_m':fm['external_prism_resolution_documentation']['factor_1_full_resolution_pixel_m'],'physical_footprint_claim':False})
 axis=d['time_to_sample_axis'];calc=math.ceil(axis['target_altitude_m']/fm['raw_sample_spacing_m']);axis_ok=(calc==axis['nearest_discrete_valid_bottom_sample']==819 and axis['selected_using_intensity'] is False);g['G4_TIME_TO_SAMPLE_AXIS']=gate('PASS_SAMPLE_819' if axis_ok else 'FAIL',{'calculated_index':calc,'stored_index':axis['nearest_discrete_valid_bottom_sample'],'altitude_m':axis['target_altitude_m'],'spacing_m':spacing,'selected_using_intensity':axis['selected_using_intensity']})
 sl=d['cd169_science_log_towfish_position'];e0=sl['endpoint_0100'];e1=sl['endpoint_0129'];f=sl['linear_interpolation_fraction_to_010725'];ilat=-(e0['tobi_decimal_latitude_s']+(e1['tobi_decimal_latitude_s']-e0['tobi_decimal_latitude_s'])*f);ilon=-(e0['tobi_decimal_longitude_w']+(e1['tobi_decimal_longitude_w']-e0['tobi_decimal_longitude_w'])*f);fr=sl['frozen_coordinate'];dlat=abs(ilat-fr['latitude']);dlon=abs(ilon-fr['longitude']);coarse_consistent=(dlat<0.001 and dlon<0.001);g['G5_COARSE_TOWFISH_GEOLOCATION']=gate('PASS_DOCUMENTED_COARSE_INTERPOLATION' if coarse_consistent else 'FAIL',{'recomputed_latitude':ilat,'recomputed_longitude':ilon,'frozen_latitude':fr['latitude'],'frozen_longitude':fr['longitude'],'absolute_delta_deg':{'latitude':dlat,'longitude':dlon},'source_reporting_resolution_deg':0.001,'per_ping_veh_nav':False})
 g['G5B_PER_PING_VEH_NAV']=gate('BLOCKED',{'ready_veh_nav_found_in_archive':d['native_archive_navigation']['ready_veh_nav_found_in_archive'],'cdf_sonar_latlon':cdf['target_header']['sonar_latlon_stored']},'PER_PING_VEH_NAV_NOT_ARCHIVED_OR_NOT_FOUND')
 proj=d['approximate_space_projection'];proj_ok=(proj['classification']=='SCIENCE_LOG_APPROX_PROJECTION' and proj['ground_fixed_proof'] is False and abs(proj['sample_819_ground_range_m']-17.523198908875056)<1e-9);g['G6_SAMPLE_TO_APPROX_SPACE']=gate('PARTIAL_APPROX' if proj_ok else 'FAIL',{'sample_index':819,'slant_range_m':proj['sample_819_slant_range_m'],'ground_range_m':proj['sample_819_ground_range_m'],'center_source':proj['center_source'],'flat_slant_geometry_used':proj['flat_slant_geometry_used'],'ground_fixed_proof':proj['ground_fixed_proof']})
 n=d['sample_819_measurement_state'];not_top=all(n[k]['in_top20_review_priority'] is False for k in ['port_sidescan','stbd_sidescan','port_swath','stbd_swath']);g['G6B_FROZEN_NADIR_SAMPLE_REVIEW_STATE']=gate('OBSERVED_NOT_STRONG_TOP20_LOCALIZATION' if not_top else 'REVIEW',{'sample_index':819,'channels':n,'scientific_absence_claim':False,'single_sample_passport_equivalence_tested':d['mnemonic_time_to_space_result']['single_sample_passport_equivalence_tested']})
 j=d['janus_gate_state_before_audit'];g['G7_GROUND_FIXED_REPLICATION']=gate('BLOCKED',{'receipt_state':j['G7_GROUND_FIXED_REPLICATION']},'NO_INDEPENDENT_EARTH_FIXED_REOBSERVATION_WITH_VALIDATED_PER_PING_FOOTPRINT')
 g['G8_GEOMETRY_CLASS']=gate('BLOCKED_NOT_TESTED',{'receipt_state':j['G8_GEOMETRY_CLASS']},'REQUIRES_GROUND_FIXED_REPLICATION')
 g['G9_PHYSICAL_ACOUSTIC_RESONANCE']=gate('BLOCKED_NOT_TESTED',{'receipt_state':j['G9_PHYSICAL_ACOUSTIC_RESONANCE'],'mnemonic_tone_is_physical_frequency':False},'NO_SUITABLE_PHYSICAL_SPECTRAL_PHASE_TEST_PERFORMED')
 fatal=any(x['state']=='FAIL' for x in g.values());out={'artifact_id':'JANUS-HANNAH-CD169-SAMPLE-SPACE-AUDIT-RUN-001-2026-08-25-v1.0','schema':'janus.cosmos.cousteau.hannah_cd169.sample_space_audit.v1','source_receipt':str(a.receipt),'audit_status':'FAIL' if fatal else 'PASS_TIME_TO_SAMPLE_AXIS__HOLD_AT_GROUND_FIXED_REPLICATION','gates':g,'janus_state':{'TIME_TO_RAW_SAMPLE_AXIS':'VALIDATED' if not fatal else 'FAILED','NEAREST_FROZEN_NADIR_SAMPLE':819 if not fatal else None,'COARSE_TOWFISH_POSITION':'DOCUMENTED_SCIENCE_LOG_INTERPOLATION' if coarse_consistent else 'FAILED','PER_PING_VEH_NAV':'BLOCKED','APPROX_SPACE_PROJECTION':'AVAILABLE_NOT_GROUND_FIXED','FROZEN_NADIR_SAMPLE_STRONG_LOCALIZATION':'NOT_OBSERVED_TOP20','GROUND_FIXED_REPLICATION':'BLOCKED','PYRAMID_LIKE_GEOMETRY':'NOT_TESTED','ACOUSTIC_RESONANCE':'NOT_TESTED','UNDERWATER_PYRAMID_DETECTED':False},'posthoc_scientific_threshold_added':False,'recentered':False,'scientific_absence_claim':False,'scientific_convergence_claim':False,'next_gate':d['next_gate'],'hard_rules':d['hard_rules']}
 a.output.parent.mkdir(parents=True,exist_ok=True);a.output.write_text(json.dumps(out,ensure_ascii=False,indent=2,sort_keys=True)+'\n',encoding='utf-8');print(json.dumps({'audit_status':out['audit_status'],'janus_state':out['janus_state']},indent=2));return 0 if not fatal else 2
if __name__=='__main__':raise SystemExit(main())
